### ISSUE TITLE
Emit 'close' on regular streams that don't have destroy()?

### ISSUE THREAD

**Issue by watson** [stream-utils/destroy#6]
In Node.js 6, streams do not have a `destroy()` function. However, pipe, pump etc will destroy the pipeline if the stream emits a `close` event, so this will have the same effect in many circumstances.

What do you say that this module falls back to emit `close` as the last option in case there's no `destroy()` function available, but there is an `emit()` function?

**Comment by dougwilson** [comment]
That's a good question, but I'm not sure this is a good thing to do. For example, there would be no guarantee that one of things are being used on the steam unless there is a way that can be checked in the implementation here before emitting it?

There are all kinds of things that can do things on an event, and emitting it on something we don't understand could cause other code to trigger incorrectly, especially if the stream already closed the underlying resource and emitted close and now this module emitted it a second time?

**Comment by dougwilson** [comment]
An example of where this can be an issue I see in just the first streams doc for Writable

https://nodejs.org/dist/latest-v10.x/docs/api/stream.html#stream_event_close

> The 'close' event is emitted when the stream and any of its underlying resources (a file descriptor, for example) have been closed. The event indicates that no more events will be emitted, and no further computation will occur.

It would seem that if this module emitted it a second time on a Writable, that would violate the API guarantees of the stream, making using this module more unsafe than it should be.

**Comment by watson** [comment]
Makes sense. Thanks for looking into this.. Let's just close this issue 😃
